project_id = "tefidquitahjjxpeowzt"

[functions.whatsapp-create-instance]
verify_jwt = true

[functions.whatsapp-get-instance-status]
verify_jwt = true

[functions.whatsapp-disconnect-instance]
verify_jwt = true

[functions.get-system-settings]
verify_jwt = false