project_id = "tefidquitahjjxpeowzt"

[functions.whatsapp-create-instance]
verify_jwt = true

[functions.whatsapp-get-instance-status]
verify_jwt = true

[functions.whatsapp-disconnect-instance]
verify_jwt = true

[functions.whatsapp-send-message]
verify_jwt = true

[functions.whatsapp-fetch-contacts]
verify_jwt = true

[functions.whatsapp-delete-agent]
verify_jwt = true

[functions.webhook-qrcode-updated]
verify_jwt = false

[functions.webhook-connection-update]
verify_jwt = false

[functions.get-system-settings]
verify_jwt = false

[functions.send-invite-whatsapp]
verify_jwt = true

[functions.update-role-from-invite]
verify_jwt = false

[functions.validate-api-token]
verify_jwt = false

[functions.public-api-available-slots]
verify_jwt = false

[functions.public-api-create-appointment]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.update-user-email]
verify_jwt = true

[functions.asaas-create-customer]
verify_jwt = true

[functions.asaas-create-subscription]
verify_jwt = true

[functions.asaas-update-customer]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false
