project_id = "tefidquitahjjxpeowzt"

[functions.whatsapp-create-instance]
verify_jwt = true

[functions.whatsapp-get-instance-status]
verify_jwt = true

[functions.whatsapp-disconnect-instance]
verify_jwt = true

[functions.whatsapp-send-message]
verify_jwt = true

[functions.whatsapp-fetch-contacts]
verify_jwt = true

[functions.get-system-settings]
verify_jwt = false

[functions.send-invite-whatsapp]
verify_jwt = true

[functions.update-role-from-invite]
verify_jwt = false
